glass project updated ... rewrote all (mac/linux) scripts using new script style...

diff --git a/bin/stones b/bin/stones
--- a/bin/stones
+++ b/bin/stones
@@ -1,51 +1,34 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - stones
-#
-# Purpose - Provide information about the installed and running stones
-#
-# Examples
-#   stones -h
-#   stones
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h]"
-  echo "List information about the installed GemStone/S products, installed stones,"
-  echo "running stones and running netldis."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0)"
-  echo ""
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h]
+List information about the installed GemStone/S products, installed stones,
+running stones and running netldis.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0)
+
+HELP
 }
 
-while getopts "h" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
-
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
+  echo "the GS_HOME environment variable needs to be defined"; exit 1
 fi
+source ${GS_HOME}/bin/shFunctions
+
+if [ $# -ne 1 ]; then
+  usage; exit 1
+fi
+
 if [ ! -e "$GS_HOME/pharo/pharo" ]; then
   $GS_HOME/bin/installPharo
 fi
@@ -53,6 +36,3 @@ fi
 # Run script
 pharo=$GS_HOME/pharo
 $pharo/pharo $pharo/todeClient.image stones
-
-# End of script
-exit 0
